#ifdef REMOTE_DEBUG
const char* remote_debug_ui_html = 
  "<!DOCTYPE html>\n"
  "<html>\n"
  "<head>\n"
  "    <title>PinMAME Advanced Debugger</title>\n"
  "    <style>\n"
  "        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #1a1a1a; color: #e0e0e0; margin: 0; display: flex; flex-direction: column; height: 100vh; overflow: hidden; }\n"
  "        header { background: #2d2d2d; padding: 10px 20px; display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #3d3d3d; }\n"
  "        .main-container { display: flex; flex: 1; overflow: hidden; }\n"
  "        .sidebar { width: 400px; background: #252526; border-right: 1px solid #3d3d3d; display: flex; flex-direction: column; overflow-y: auto; }\n"
  "        .content { flex: 1; display: flex; flex-direction: column; padding: 10px; overflow-y: auto; background: #1e1e1e; }\n"
  "        .panel { background: #2d2d2d; border: 1px solid #3d3d3d; border-radius: 4px; margin-bottom: 10px; padding: 12px; }\n"
  "        .panel h2 { margin-top: 0; font-size: 0.9rem; border-bottom: 1px solid #3d3d3d; padding-bottom: 8px; color: #4fc1ff; text-transform: uppercase; letter-spacing: 1px; }\n"
  "        .btn { background: #0e639c; color: white; border: none; padding: 4px 10px; cursor: pointer; border-radius: 2px; font-size: 0.8rem; margin-left: 2px; }\n"
  "        .btn:hover { background: #1177bb; }\n"
  "        .btn-danger { background: #a1260d; }\n"
  "        .btn-success { background: #388a34; }\n"
  "        .btn-cabinet { background: #444; border: 1px solid #666; width: 60px; height: 30px; margin: 2px; font-weight: bold; font-size: 0.7rem; }\n"
  "        .btn-cabinet:active { background: #00ff00; color: #000; }\n"
  "        .reg-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 6px; font-family: 'Consolas', monospace; }\n"
  "        .reg-item { background: #1e1e1e; padding: 4px 8px; border-radius: 2px; display: flex; justify-content: space-between; border-left: 3px solid #4fc1ff; align-items: center; }\n"
  "        .reg-label { color: #858585; font-size: 0.75rem; }\n"
  "        .reg-val { color: #dcdcaa; font-weight: bold; font-size: 0.85rem; }\n"
  "        .reg-dec { color: #6a9955; font-size: 0.7rem; margin-left: 5px; }\n"
  "        .flags-grid { display: flex; gap: 2px; font-family: 'Consolas', monospace; margin-top: 10px; }\n"
  "        .flag { flex: 1; text-align: center; background: #333; padding: 4px 0; border-radius: 2px; font-size: 0.75rem; color: #555; }\n"
  "        .flag.active { background: #388a34; color: #fff; font-weight: bold; }\n"
  "        .hex-table, .dasm-table { font-family: 'Consolas', monospace; border-collapse: collapse; width: 100%; font-size: 0.85rem; background: #1e1e1e; }\n"
  "        .hex-table td, .dasm-table td { padding: 3px 8px; border: 1px solid #2d2d2d; }\n"
  "        .addr-col { color: #858585; width: 70px; background: #252526; text-align: right; padding-right: 12px !important; }\n"
  "        .hex-byte { cursor: pointer; text-align: center; width: 30px; color: #9cdcfe; }\n"
  "        .hex-ascii { color: #6a9955; width: 120px; border-left: 2px solid #3d3d3d !important; font-size: 0.8rem; }\n"
  "        .current-pc { background: #3e3e10 !important; }\n"
  "        #dmd-canvas { background: #000; width: 100%; image-rendering: pixelated; border: 1px solid #444; }\n"
  "        #seg-canvas { background: #000; width: 100%; border: 1px solid #444; }\n"
  "        .status-tag { padding: 3px 10px; border-radius: 12px; font-size: 0.75rem; background: #444; margin-right: 12px; font-weight: bold; }\n"
  "        .status-paused { background: #a1260d; color: white; }\n"
  "        .status-running { background: #388a34; color: white; }\n"
  "        input { background: #3c3c3c; border: 1px solid #3d3d3d; color: #fff; padding: 4px 8px; border-radius: 2px; outline: none; font-family: 'Consolas', monospace; }\n"
  "        .tool-bar { margin-bottom: 10px; display: flex; gap: 10px; align-items: center; background: #252526; padding: 8px; border-radius: 4px; }\n"
  "        #console-log { background: #000; color: #6a9955; font-family: 'Consolas', monospace; font-size: 0.85rem; height: 120px; overflow-y: scroll; padding: 10px; border: 1px solid #333; margin-top: 10px; }\n"
  "        .console-line { margin-bottom: 2px; border-bottom: 1px solid #111; }\n"
  "        .matrix { display: grid; grid-template-columns: repeat(8, 1fr); gap: 2px; background: #333; padding: 4px; border-radius: 2px; }\n"
  "        .matrix-dot { width: 14px; height: 14px; background: #222; border-radius: 2px; border: 1px solid #444; }\n"
  "        .matrix-dot.active-lamp { background: #ffff00; box-shadow: 0 0 5px #ffff00; }\n"
  "        .matrix-dot.active-sw { background: #00ff00; }\n"
  "        .matrix-dot.active-sol { background: #ff0000; box-shadow: 0 0 5px #ff0000; }\n"
  "        .sw-clickable { cursor: pointer; }\n"
  "        .point-item { display: flex; justify-content: space-between; align-items: center; padding: 4px; border-bottom: 1px solid #333; font-size: 0.8rem; }\n"
  "    </style>\n"
  "</head>\n"
  "<body>\n"
  "    <header>\n"
  "        <div><span style=\"color: #4fc1ff; font-weight: bold; font-size: 1.1rem;\">PinMAME Multi-Sys Debug</span><span id=\"game-title\" style=\"margin-left: 15px; color: #aaaaaa; font-size: 0.9rem;\">...</span></div>\n"
  "        <div><span id=\"status-mode\" class=\"status-tag\">OFFLINE</span>\n"
  "            <button class=\"btn\" onclick=\"control('pause')\">Pause</button><button class=\"btn\" onclick=\"control('resume')\">Resume</button><button class=\"btn\" onclick=\"control('step')\">Step</button><button class=\"btn btn-success\" onclick=\"control('stepover')\">Step Over</button><button class=\"btn btn-danger\" onclick=\"emulatorExit()\">Exit</button>\n"
  "        </div>\n"
  "    </header>\n"
  "    <div class=\"main-container\">\n"
  "        <div class=\"sidebar\">\n"
  "            <div id=\"display-panel\" class=\"panel\" style=\"margin: 10px;\">\n"
  "                <h2 id=\"display-title\">System Display</h2>\n"
  "                <div id=\"dmd-container\"><canvas id=\"dmd-canvas\"></canvas></div>\n"
  "                <div id=\"seg-container\" style=\"display:none;\"><canvas id=\"seg-canvas\"></canvas></div>\n"
  "                <div style=\"margin-top: 5px; font-size: 0.7rem; color: #858585;\"><span id=\"dmd-res\">0x0</span> | <input type=\"checkbox\" id=\"auto-refresh-dmd\" checked> Live</div>\n"
  "            </div>\n"
  "            <div id=\"cpu-panels-container\"></div>\n"
  "            <div class=\"panel\" style=\"margin: 10px;\">\n"
  "                <h2>Cabinet & Service</h2>\n"
  "                <div style=\"display: grid; grid-template-columns: repeat(4, 1fr); gap: 5px;\">\n"
  "                    <button class=\"btn btn-cabinet\" onmousedown=\"pulseSw(1,1)\" onmouseup=\"pulseSw(1,0)\">COIN</button>\n"
  "                    <button class=\"btn btn-cabinet\" onmousedown=\"pulseSw(13,1)\" onmouseup=\"pulseSw(13,0)\" style=\"background: #0e639c;\">START</button>\n"
  "                    <button class=\"btn btn-cabinet\" onmousedown=\"pulseSw(5,1)\" onmouseup=\"pulseSw(5,0)\">ESC</button>\n"
  "                    <button class=\"btn btn-cabinet\" onmousedown=\"pulseSw(6,1)\" onmouseup=\"pulseSw(6,0)\">-</button>\n"
  "                    <button class=\"btn btn-cabinet\" onmousedown=\"pulseSw(7,1)\" onmouseup=\"pulseSw(7,0)\">+</button>\n"
  "                    <button class=\"btn btn-cabinet\" onmousedown=\"pulseSw(8,1)\" onmouseup=\"pulseSw(8,0)\">ENT</button>\n"
  "                </div>\n"
  "            </div>\n"
  "            <div class=\"panel\" style=\"margin: 10px;\"><h2>System Info</h2><div class=\"reg-item\"><span class=\"reg-label\">Active Bank</span><span id=\"wpc-bank\" class=\"reg-val\">?</span></div></div>\n"
  "            <div class=\"panel\" style=\"margin: 10px;\">\n"
  "                <h2>Matrix Visualizer</h2>\n"
  "                <div style=\"font-size: 0.7rem; color: #888; margin-bottom: 5px;\">Lamps (8x8)</div>\n"
  "                <div id=\"matrix-lamps\" class=\"matrix\"></div>\n"
  "                <div style=\"font-size: 0.7rem; color: #888; margin: 10px 0 5px 0;\">Switches (8x8)</div>\n"
  "                <div id=\"matrix-sw\" class=\"matrix\"></div>\n"
  "                <div style=\"font-size: 0.7rem; color: #888; margin: 10px 0 5px 0;\">Solenoids (32)</div>\n"
  "                <div id=\"matrix-sol\" class=\"matrix\" style=\"grid-template-columns: repeat(8, 1fr);\"></div>\n"
  "                <div style=\"font-size: 0.7rem; color: #888; margin: 10px 0 5px 0;\">Direct (8)</div>\n"
  "                <div id=\"matrix-ded\" class=\"matrix\" style=\"grid-template-columns: repeat(8, 1fr);\"></div>\n"
  "            </div>\n"
  "        </div>\n"
  "        <div class=\"content\">\n"
  "            <div class=\"panel\" style=\"display: flex; flex-direction: column; height: 350px;\">\n"
  "                <h2>Disassembler</h2>\n"
  "                <div class=\"tool-bar\">Addr: <input type=\"text\" id=\"dasm-addr\" value=\"0x0000\" style=\"width: 70px;\"> CPU: <input type=\"number\" id=\"dasm-cpu\" value=\"0\" style=\"width: 35px;\"> <button class=\"btn\" onclick=\"refreshDasm()\">Go</button><button class=\"btn\" onclick=\"followPC()\">Follow PC</button></div>\n"
  "                <div style=\"flex: 1; overflow-y: auto;\"><table class=\"dasm-table\" id=\"dasm-view\"></table></div>\n"
  "            </div>\n"
  "            <div class=\"panel\">\n"
  "                <h2>Control Center</h2>\n"
  "                <div class=\"row\">\n"
  "                    <div class=\"col\">\n"
  "                        <div style=\"margin-bottom: 5px;\"><input type=\"text\" id=\"bp-addr\" placeholder=\"Addr\" style=\"width: 60px;\"> <button class=\"btn btn-success btn-small\" onclick=\"addPoint('bp')\">+BP</button> <select id=\"wp-mode\" style=\"background:#3c3c3c;color:#fff;\"><option value=\"1\">R</option><option value=\"2\">W</option><option value=\"3\">RW</option></select> <button class=\"btn btn-success btn-small\" onclick=\"addPoint('wp')\">+WP</button></div>\n"
  "                        <div id=\"point-list\" style=\"max-height: 100px; overflow-y: auto; background: #111;\"></div>\n"
  "                    </div>\n"
  "                    <div class=\"col\">\n"
  "                        <div style=\"display:flex;gap:5px;margin-bottom:10px;\"><input type=\"text\" id=\"cli-cmd\" placeholder=\"Classic MAME Command...\" style=\"flex:1;\"><button class=\"btn\" onclick=\"runCLI()\">Exec</button></div>\n"
  "                        <button class=\"btn btn-danger btn-small\" onclick=\"nvramClear()\">Wipe NVRAM & Reset</button>\n"
  "                    </div>\n"
  "                </div>\n"
  "                <div id=\"console-log\"></div>\n"
  "            </div>\n"
  "            <div class=\"panel\">\n"
  "                <h2>Memory Hex Editor & Search</h2>\n"
  "                <div class=\"tool-bar\">\n"
  "                    Addr: <input type=\"text\" id=\"mem-addr\" value=\"0x0000\" style=\"width: 70px;\"> \n"
  "                    Size: <input type=\"number\" id=\"mem-size\" value=\"256\" style=\"width: 60px;\"> \n"
  "                    CPU: <input type=\"number\" id=\"mem-cpu\" value=\"0\" style=\"width: 35px;\"> \n"
  "                    <button class=\"btn\" onclick=\"refreshMemory()\">Read</button>\n"
  "                </div>\n"
  "                <div class=\"tool-bar\" style=\"background: #2d2d2d; border: 1px dashed #444;\">\n"
  "                    Search HEX: <input type=\"text\" id=\"search-pat\" placeholder=\"e.g. 414243\" style=\"flex:1;\">\n"
  "                    <button class=\"btn btn-success\" onclick=\"runSearch()\">Find</button>\n"
  "                </div>\n"
  "                <div id=\"hex-container\" style=\"overflow-x: auto; background: #1e1e1e; max-height: 180px; overflow-y: auto;\"><table class=\"hex-table\" id=\"hex-view\"></table></div>\n"
  "            </div>\n"
  "        </div>\n"
  "    </div>\n"
  "    <script>\n"
  "        let isPaused = false; let lastPC = 0; let dmdWidth = 128; let dmdHeight = 32;\n"
  "        let switchStates = new Array(64).fill(false); let dedicatedStates = new Array(8).fill(false);\n"
  "\n"
  "        function control(cmd) { fetch('/api/debugger/control?cmd=' + cmd).then(r => r.json()).then(updateStatus); }\n"
  "        function pulseSw(sw, val) { fetch(`/api/input?sw=${sw}&val=${val}`).then(updateStatus); }\n"
  "        function nvramClear() { if(confirm(\"Wipe NVRAM?\")) fetch('/api/debugger/nvram?cmd=clear').then(() => updateStatus()); }\n"
  "        function emulatorExit() { if(confirm(\"Exit Emulator?\")) { fetch('/api/debugger/control?cmd=exit'); document.body.innerHTML = \"<h1>Disconnected</h1>\"; } }\n"
  "        \n"
  "        function runSearch() {\n"
  "            const addr = document.getElementById('mem-addr').value; const pat = document.getElementById('search-pat').value; const cpu = document.getElementById('mem-cpu').value;\n"
  "            if(!pat) return;\n"
  "            fetch(`/api/debugger/memory/find?addr=${addr}&size=0x8000&pattern=${pat}&cpu=${cpu}`).then(r => r.json()).then(data => {\n"
  "                if(data.status === 'ok') { const found = '0x' + data.found.toString(16).toUpperCase(); document.getElementById('mem-addr').value = found; document.getElementById('dasm-addr').value = found; refreshMemory(); refreshDasm(); alert(\"Pattern found at \" + found); }\n"
  "                else { alert(\"Pattern not found.\"); }\n"
  "            });\n"
  "        }\n"
  "\n"
  "        function toggleSwitch(idx, isDedicated) {\n"
  "            const current = isDedicated ? dedicatedStates[idx] : switchStates[idx]; const newVal = current ? 0 : 1;\n"
  "            let swNum; if (isDedicated) swNum = idx + 1; else { const col = Math.floor(idx/8); const row = idx%8; if (col === 0) swNum = row + 1; else swNum = col * 10 + row + 1; }\n"
  "            fetch(`/api/input?sw=${swNum}&val=${newVal}`).then(updateStatus);\n"
  "        }\n"
  "\n"
  "        function initMatrices() {\n"
  "            const l = document.getElementById('matrix-lamps'); const s = document.getElementById('matrix-sw'); const sl = document.getElementById('matrix-sol'); const dd = document.getElementById('matrix-ded');\n"
  "            l.innerHTML = ''; s.innerHTML = ''; sl.innerHTML = ''; dd.innerHTML = '';\n"
  "            for(let i=0; i<64; i++) { l.innerHTML += `<div id=\"lamp-${i}\" class=\"matrix-dot\"></div>`; s.innerHTML += `<div id=\"sw-${i}\" class=\"matrix-dot sw-clickable\" onclick=\"toggleSwitch(${i}, false)\"></div>`; }\n"
  "            for(let i=0; i<32; i++) { sl.innerHTML += `<div id=\"sol-${i}\" class=\"matrix-dot\"></div>`; }\n"
  "            for(let i=0; i<8; i++) { dd.innerHTML += `<div id=\"ded-${i}\" class=\"matrix-dot sw-clickable\" onclick=\"toggleSwitch(${i}, true)\"></div>`; }\n"
  "        }\n"
  "\n"
  "        function drawSegment(ctx, x, y, val) {\n"
  "            ctx.strokeStyle = \"#ff2200\"; ctx.lineWidth = 2.2; ctx.lineCap = \"round\";\n"
  "            ctx.shadowBlur = 3; ctx.shadowColor = \"#ff0000\";\n"
  "            \n"
  "            // GROUND TRUTH MAPPING FROM VPINBALL usbalphanumeric.h\n"
  "            const segs = [\n"
  "                [2,0, 13,0],      // Bit 0: a (top)\n"
  "                [15,2, 15,11],    // Bit 1: b (right top)\n"
  "                [15,14, 15,23],   // Bit 2: c (right bottom)\n"
  "                [2,25, 13,25],    // Bit 3: d (bottom)\n"
  "                [0,14, 0,23],     // Bit 4: e (left bottom)\n"
  "                [0,2, 0,11],      // Bit 5: f (left top)\n"
  "                [2,12.5, 7,12.5], // Bit 6: g1 (middle left)\n"
  "                null,             // Bit 7: Comma (handled below)\n"
  "                [2,2, 6.5,11.5],  // Bit 8: j (diag top left)\n"
  "                [7.5,2, 7.5,11],  // Bit 9: h (center top)\n"
  "                [13,2, 8.5,11.5], // Bit 10: k (diag top right)\n"
  "                [8,12.5, 13,12.5],// Bit 11: g2 (middle right)\n"
  "                [13,23, 8.5,13.5],// Bit 12: m (diag bottom right)\n"
  "                [7.5,14, 7.5,23], // Bit 13: i (center bottom)\n"
  "                [2,23, 6.5,13.5], // Bit 14: l (diag bottom left)\n"
  "                null              // Bit 15: Period (handled below)\n"
  "            ];\n"
  "\n"
  "            for (let bit = 0; bit < 16; bit++) {\n"
  "                if (val & (1 << bit)) {\n"
  "                    const pts = segs[bit];\n"
  "                    if (pts) {\n"
  "                        ctx.beginPath(); ctx.moveTo(x + pts[0], y + pts[1]); ctx.lineTo(x + pts[2], y + pts[3]); ctx.stroke();\n"
  "                    }\n"
  "                }\n"
  "            }\n"
  "            if (val & 0x8000) { // Bit 15: Period\n"
  "                ctx.fillStyle = \"#ff2200\"; ctx.beginPath(); ctx.arc(x + 17, y + 25, 1.5, 0, Math.PI*2); ctx.fill();\n"
  "            }\n"
  "            if (val & 0x0080) { // Bit 7: Comma\n"
  "                ctx.beginPath(); ctx.moveTo(x + 17, y + 25); ctx.lineTo(x + 14, y + 30); ctx.stroke();\n"
  "            }\n"
  "        }\n"
  "\n"
  "        function renderSegments(hex) {\n"
  "            const canvas = document.getElementById('seg-canvas'); const ctx = canvas.getContext('2d');\n"
  "            canvas.width = 380; canvas.height = 80; ctx.clearRect(0, 0, canvas.width, canvas.height);\n"
  "            for (let i = 0; i < 32; i++) {\n"
  "                const val = parseInt(hex.substr(i*4, 4), 16); if (isNaN(val)) continue;\n"
  "                const x = (i % 16) * 22 + 10; const y = Math.floor(i / 16) * 35 + 10;\n"
  "                drawSegment(ctx, x, y, val);\n"
  "            }\n"
  "        }\n"
  "\n"
  "        function updateStatus() {\n"
  "            fetch('/api/info').then(r => r.json()).then(data => {\n"
  "                document.getElementById('game-title').innerText = data.game; document.getElementById('wpc-bank').innerText = data.wpc_bank === -1 ? \"N/A\" : \"0x\" + data.wpc_bank.toString(16).toUpperCase();\n"
  "                isPaused = data.paused; const tag = document.getElementById('status-mode'); tag.innerText = isPaused ? \"PAUSED\" : \"RUNNING\"; tag.className = \"status-tag \" + (isPaused ? \"status-paused\" : \"status-running\");\n"
  "                \n"
  "                if (data.segments && data.segments.replace(/0/g,'') !== '') {\n"
  "                    document.getElementById('seg-container').style.display = 'block'; document.getElementById('dmd-container').style.display = 'none';\n"
  "                    renderSegments(data.segments);\n"
  "                } else {\n"
  "                    document.getElementById('seg-container').style.display = 'none'; document.getElementById('dmd-container').style.display = 'block';\n"
  "                }\n"
  "\n"
  "                const lamps = data.lamps; const sws = data.switches;\n"
  "                for(let i=0; i<64; i++) {\n"
  "                    const col = Math.floor(i/8); const bit = i%8; const isActive = (parseInt(sws.substr(col*2, 2), 16) & (1<<bit)); switchStates[i] = isActive;\n"
  "                    document.getElementById(`lamp-${i}`).className = `matrix-dot ${(parseInt(lamps.substr(col*2, 2), 16) & (1<<bit))?'active-lamp':''}`;\n"
  "                    document.getElementById(`sw-${i}`).className = `matrix-dot sw-clickable ${isActive?'active-sw':''}`;\n"
  "                }\n"
  "                for(let i=0; i<32; i++) { document.getElementById(`sol-${i}`).className = `matrix-dot ${(data.solenoids & (1<<i))?'active-sol':''}`; }\n"
  "                for(let i=0; i<8; i++) { const isActive = (data.dedicated & (1<<i)); dedicatedStates[i] = isActive; document.getElementById(`ded-${i}`).className = `matrix-dot sw-clickable ${isActive?'active-sw':''}`; }\n"
  "            }).catch(() => { document.getElementById('status-mode').innerText = \"OFFLINE\"; });\n"
  "        }\n"
  "\n"
  "        function refreshDMD() {\n"
  "            if (document.getElementById('dmd-container').style.display === 'none') return;\n"
  "            fetch('/api/dmd/info').then(r => r.json()).then(info => {\n"
  "                if (info.error) return;\n"
  "                dmdWidth = info.width; dmdHeight = info.height; document.getElementById('dmd-res').innerText = `${dmdWidth}x${dmdHeight}`; return fetch('/api/dmd/raw');\n"
  "            }).then(r => r ? r.arrayBuffer() : null).then(buf => {\n"
  "                if (!buf) return;\n"
  "                const canvas = document.getElementById('dmd-canvas'); const ctx = canvas.getContext('2d'); canvas.width = dmdWidth; canvas.height = dmdHeight;\n"
  "                const imgData = ctx.createImageData(dmdWidth, dmdHeight); const bytes = new Uint8Array(buf);\n"
  "                for (let i = 0; i < bytes.length; i++) { const v = bytes[i]; const idx = i * 4; imgData.data[idx] = 255; imgData.data[idx+1] = 150; imgData.data[idx+2] = 0; imgData.data[idx+3] = v; }\n"
  "                ctx.putImageData(imgData, 0, 0);\n"
  "            }).catch(() => {});\n"
  "        }\n"
  "\n"
  "        function refreshState() { fetch('/api/debugger/state').then(r => r.json()).then(data => { const container = document.getElementById('cpu-panels-container'); container.innerHTML = ''; if(!data.cpus) return; data.cpus.forEach(cpu => { if (cpu.id === 0 && lastPC !== cpu.pc) { lastPC = cpu.pc; if (isPaused) followPC(); } const panel = document.createElement('div'); panel.className = 'panel'; panel.style.margin = '5px 10px'; let regHtml = `<div class=\"reg-grid\">`; for (const [reg, val] of Object.entries(cpu)) { if (reg === 'id' || reg === 'type') continue; regHtml += `<div class=\"reg-item\"><span class=\"reg-label\">${reg.toUpperCase()}</span><div><span class=\"reg-val\">${val.toString(16).toUpperCase()}</span><span class=\"reg-dec\">${val}</span></div></div>`; } if (cpu.cc !== undefined) { const flags = ['C', 'V', 'Z', 'N', 'I', 'H', 'F', 'E']; regHtml += `</div><div class=\"flags-grid\">` + flags.map((f, i) => `<div class=\"flag ${ (cpu.cc & (1 << i)) ? 'active' : '' }\">${f}</div>`).reverse().join('') + `</div>`; } else { regHtml += `</div>`; } panel.innerHTML = `<h2>CPU ${cpu.id} (${cpu.type === 14 ? 'M6809' : 'ADSP'})</h2>` + regHtml; container.appendChild(panel); }); }); }\n"
  "        function refreshDasm() { const addr = document.getElementById('dasm-addr').value; const cpu = document.getElementById('dasm-cpu').value; fetch(`/api/debugger/dasm?addr=${addr}&lines=25&cpu=${cpu}`).then(r => r.json()).then(data => { const table = document.getElementById('dasm-view'); table.innerHTML = ''; if (!data.lines) return; data.lines.forEach(line => { const row = table.insertRow(); const a = parseInt(line.addr); if (a === lastPC) row.className = 'current-pc'; const c1 = row.insertCell(); c1.className = 'addr-col'; c1.innerText = a.toString(16).toUpperCase().padStart(4, '0'); row.insertCell().innerText = line.text; row.onclick = () => { document.getElementById('bp-addr').value = '0x' + a.toString(16).toUpperCase(); }; }); }); }\n"
  "        function followPC() { document.getElementById('dasm-addr').value = '0x' + lastPC.toString(16).toUpperCase(); refreshDasm(); }\n"
  "        function refreshMessages() { fetch('/api/debugger/messages').then(r => r.json()).then(data => { const log = document.getElementById('console-log'); log.innerHTML = ''; data.messages.forEach(m => { const div = document.createElement('div'); div.className = 'console-line'; div.innerText = `> ${m}`; log.appendChild(div); }); log.scrollTop = log.scrollHeight; }); }\n"
  "        function refreshPoints() { fetch('/api/debugger/points').then(r => r.json()).then(data => { const list = document.getElementById('point-list'); list.innerHTML = ''; data.breakpoints.forEach(p => addPointRow(list, 'bp', p.idx, p.addr, p.enabled)); data.watchpoints.forEach(p => addPointRow(list, 'wp', p.idx, p.addr, p.enabled, p.mode)); }); }\n"
  "        function addPointRow(container, type, idx, addr, enabled, mode) { const div = document.createElement('div'); div.className = 'point-item'; const label = mode ? `WP(${['','R','W','RW'][mode]})` : 'BP'; div.innerHTML = `<span class=\"point-addr ${enabled?'':'point-disabled'}\">${label} 0x${addr.toString(16).toUpperCase()}</span><div><button class=\"btn btn-small\" onclick=\"pointAction('toggle','${type}',${idx})\">${enabled?'Off':'On'}</button><button class=\"btn btn-danger btn-small\" onclick=\"pointAction('delete','${type}',${idx})\">X</button></div>`; container.appendChild(div); }\n"
  "        function pointAction(cmd, type, idx) { fetch(`/api/debugger/points?cmd=${cmd}&type=${type}&idx=${idx}`).then(() => refreshPoints()); }\n"
  "        function addPoint(type) { const addr = document.getElementById('bp-addr').value; const url = type === 'bp' ? `/api/debugger/breakpoints?cmd=add&addr=${addr}` : `/api/debugger/watchpoints?cmd=add&addr=${addr}&mode=${document.getElementById('wp-mode').value}`; fetch(url).then(() => { refreshPoints(); refreshMessages(); }); }\n"
  "        function refreshMemory() { const addr = document.getElementById('mem-addr').value; const size = document.getElementById('mem-size').value; const cpu = document.getElementById('mem-cpu').value; fetch(`/api/debugger/memory?addr=${addr}&size=${size}&cpu=${cpu}`).then(r => r.json()).then(data => { const table = document.getElementById('hex-view'); table.innerHTML = ''; if(!data.data) return; let row; let ascii = ''; data.data.forEach((byte, i) => { if (i % 16 === 0) { if (i > 0) { const c = row.insertCell(); c.className = 'hex-ascii'; c.innerText = ascii; } row = table.insertRow(); ascii = ''; const aCell = row.insertCell(); aCell.className = 'addr-col'; aCell.innerText = (parseInt(data.addr) + i).toString(16).toUpperCase().padStart(4, '0'); } const c = row.insertCell(); c.className = 'hex-byte'; c.innerText = byte.toString(16).toUpperCase().padStart(2, '0'); c.onclick = () => { const v = prompt(`Edit 0x${(parseInt(data.addr)+i).toString(16)}`, `0x${byte.toString(16)}`); if(v) fetch(`/api/debugger/memory/write?addr=${parseInt(data.addr)+i}&val=${v}&cpu=${cpu}`).then(() => refreshMemory()); }; ascii += (byte >= 32 && byte <= 126) ? String.fromCharCode(byte) : '.'; }); if (row) { while(row.cells.length < 17) row.insertCell(); row.cells[16].className = 'hex-ascii'; row.cells[16].innerText = ascii; } }); }\n"
  "        function runCLI() { const cmd = document.getElementById('cli-cmd').value; if(!cmd) return; fetch('/api/debugger/command?cmd=' + encodeURIComponent(cmd)).then(r => r.json()).then(() => { document.getElementById('cli-cmd').value = ''; refreshMessages(); refreshPoints(); updateStatus(); refreshState(); refreshMemory(); refreshDasm(); }); }\n"
  "        document.getElementById('cli-cmd').onkeydown = (e) => { if(e.key === 'Enter') runCLI(); };\n"
  "        initMatrices(); setInterval(updateStatus, 1000); setInterval(refreshState, 1000); setInterval(refreshMessages, 1000); setInterval(refreshPoints, 2000); setInterval(() => { if (document.getElementById('auto-refresh-dmd').checked) refreshDMD(); }, 500); updateStatus(); refreshState(); refreshMemory(); refreshDasm(); refreshPoints();\n"
  "    </script>\n"
  "</body>\n"
  "</html>\n"
;
#endif
